### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by MarkTiedemann**

### CODE REVIEW

**Comment by MarkTiedemann** [comment]
I guess the readme should also be updated to include the `Error: Unsupported os: {{os}}`. Or should we just gracefully do nothing if the os is not supported?

**Comment by sindresorhus** [comment]
We can just fail gracefully. You also need to mention Windows support in the readme.

**Comment by MarkTiedemann** [comment]
Well, I changed my mind. I think we should `throw`.

If the exec fails, it's gonna throw anyways. And if we do `try { ... } catch (error) { /* log error in some way */ }` we just swallow useful info and make it harder to test.

I guess we could also just do a Promise API and exec async. Users could then decide what to do with the error in their `.catch()`.

What do you think?

**Comment by sindresorhus** [comment]
I'm ok with throwing too, but it should stay synchronous.

**Comment by MarkTiedemann** [comment]
Okay, I kept it sync.

I also switched from `return` to `break` so it doesn't return a `Buffer`.

**Comment by sindresorhus** [comment]
👍

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/lock-cli/commit/4aa7c339c9a0d7d8d52efc325a97c2693690155f

**Pull request merged**
